### ISSUE TITLE
Damaged armor dropped by mobs has negative durability.

### ISSUE THREAD

**Issue by Tokeli** [Randores/Randores2#2]
Forge 14.22.1.2479
Randores-2.0.0-Pre2
Any armor dropped by mobs seems to have an... inverted durability. "-4000 / 1600", "-3583 / 1300", "-517 / 1600".

**Comment by SocraticPhoenix** [comment]
Weird, I remember this bug happening in the development stages of Randores 1, but I guess it resurfaced somehow... I'll look into it

**Comment by Tokeli** [comment]
I sorta feel like I should have combined these two bug reports, but they seemed like separate issues.

The negative-armor bug seems to only occur in multiplayer, and is present in 2459 as well. I had a helmet with 0 durability left get dropped in singleplayer, everything else was okay. In multiplayer, some armor is fine, but most are in the negatives.

**Comment by SocraticPhoenix** [comment]
It sounds like the bugs are related, but they are separate issues, so it's quite all right. I'm rather busy today, but I will try and figure them out. Thanks for the report!

**Comment by SocraticPhoenix** [comment]
It may have been 20 days.... but today I finally sat down for about an hour and figured out that I was missing a single line of code to update the material definitions on the client side... Sorry I didn't do that sooner xD
